apiVersion: v1 # versão da api, consegue separar os objetos por versão
kind: Pod # O objeto que vocÇe vai utilizar
metadata: # Metadados do POD, labels, atributos e nome do objeto
  name: meupod
  labels:
    app: web
    versao: blue
spec: #  Especificação do objeto. O que terá: containers e etc...
  containers:
    - name: web
      image: kubedevio/web-color:blue
      ports:
        - name: http
          containerPort: 80
          protocol: TCP

---
apiVersion: v1 # versão da api, consegue separar os objetos por versão
kind: Pod # O objeto que vocÇe vai utilizar
metadata: # Metadados do POD, labels, atributos e nome do objeto
  name: meupod2
  labels:
    app: web
    versao: green
spec: #  Especificação do objeto. O que terá: containers e etc...
  containers:
    - name: web
      image: kubedevio/web-color:green
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
